# Generated by Django 3.2.4 on 2022-11-24 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200911_0907'),
        ('auctions', '0002_remove_bidding_auction'),
        ('auctions', '0004_auto_20200902_0121'),
    ]

    operations = [
    ]
